export const LOAD_COUNTRIES_SUCCESS = 'LOAD_COUNTRIES_SUCCESS';  
export const COUNTRIES_LOADING = 'COUNTRIES_LOADING';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';  
export const USERS_LOADING = 'USERS_LOADING';  
export const USERS_FAILURE = 'USERS_FAILURE';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';  
export const USER_LOADING = 'USER_LOADING';  
export const USER_FAILURE = 'USER_FAILURE'; 
export const USER_REMOVE = 'USER_REMOVE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const UPLOAD_FILE = 'UPLOAD_FILE';




export const LOAD_ASSIGNSMNT_SUCCESS = 'LOAD_ASSIGN_SUCCESS';  
export const ASSIGNSMNT_LOADING = 'ASSIGNS_LOADING';
export const ASSIGNS_COUNT = 'ASSIGNS_COUNT'; 
